### ISSUE TITLE
Licensing land-mine.

### ISSUE THREAD

**Issue by MrJoy** [roo-rb/roo-xls#17]
The author of the `spreadsheet` gem seems to have a fairly bizarre interpretation of the GPLv3, and has been [unwilling to clarify](https://github.com/zdavatz/spreadsheet/issues/167) that interpretation.  [His interpretation](http://spreadsheet.ch/2014/10/24/using-ruby-spreadsheet-on-heroku-with-dynos/) looks to me like he has confused the GPLv3 with the GNU AGPL.

You may wish to note in the README that while the license is presented as being GPLv3 that the author seems to interpret it more like the GNU AGPL and that they should plan accordingly as they will (apparently) need a commercial license if they wish to run a public-facing service using this code.

**Comment by stevendaniels** [comment]
Thanks for mentioning this. The licensing issue for spreadsheet is terribly complex.

`spreadsheet` gem is based on `spreadsheet-excel` which uses the [Ruby License](https://en.wikipedia.org/wiki/Ruby_License). At the time spreadsheet was written, the Ruby License allowed "covered software to be distributed under the terms of the GPL instead of those of the Ruby License itself."

I agree his interpretation does not seem to reflect the GPLv3, but I offer no opinion on how others should use the `spreadsheet` gem. 

Frankly, I would love to write an MIT-licensed gem for reading XLS files--if someone was paying me to do so (via kickstarter or other means). 

I'd happily add request a PR updating the README language.

**Comment by MrJoy** [comment]
PR #18 submitted.

It does take a stance on how to proceed that would show an abundance of caution for the matter, by taking the most conservative approach possible here.  Users are of course free to take a chance (with or without proper counsel) on how a court would handle the ambiguity but this approach should be the safest option short of "don't use `spreadsheet` (and by extension, `roo-xls`)."

**Comment by stevendaniels** [comment]
Modified your language and created this commit. 

https://github.com/roo-rb/roo-xls/commit/6449b5de121420cb8981df876acf984b547d7703

Thanks for your help!

**Comment by jetaggart** [comment]
I appreciate the discussion. After looking through the spreadsheet gem license, we've decided that it's way to risky to depend on that in any way. We've started building our own xls parser. Any help would be appreciated. Obviously, it's still rough, but we've got basic spreadsheets parsed. Just wanted to throw this out there in case someone was thinking of undertaking this, so there would not be duplicate effort.

The repo is here: https://github.com/p2bi/read_xls

If you'd like to help I'd be happy to orient you in the code.
